package io.oicp.yorick61c.domain;

import java.io.Serializable;
import java.math.BigDecimal;

public class EbOrderDetail implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_order_detail.eod_id
     *
     * @mbggenerated
     */
    private Integer eodId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_order_detail.eo_id
     *
     * @mbggenerated
     */
    private Integer eoId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_order_detail.ep_id
     *
     * @mbggenerated
     */
    private Integer epId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_order_detail.eod_quantity
     *
     * @mbggenerated
     */
    private Integer eodQuantity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_order_detail.eod_cost
     *
     * @mbggenerated
     */
    private BigDecimal eodCost;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table eb_order_detail
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_order_detail.eod_id
     *
     * @return the value of eb_order_detail.eod_id
     *
     * @mbggenerated
     */
    public Integer getEodId() {
        return eodId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_order_detail.eod_id
     *
     * @param eodId the value for eb_order_detail.eod_id
     *
     * @mbggenerated
     */
    public void setEodId(Integer eodId) {
        this.eodId = eodId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_order_detail.eo_id
     *
     * @return the value of eb_order_detail.eo_id
     *
     * @mbggenerated
     */
    public Integer getEoId() {
        return eoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_order_detail.eo_id
     *
     * @param eoId the value for eb_order_detail.eo_id
     *
     * @mbggenerated
     */
    public void setEoId(Integer eoId) {
        this.eoId = eoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_order_detail.ep_id
     *
     * @return the value of eb_order_detail.ep_id
     *
     * @mbggenerated
     */
    public Integer getEpId() {
        return epId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_order_detail.ep_id
     *
     * @param epId the value for eb_order_detail.ep_id
     *
     * @mbggenerated
     */
    public void setEpId(Integer epId) {
        this.epId = epId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_order_detail.eod_quantity
     *
     * @return the value of eb_order_detail.eod_quantity
     *
     * @mbggenerated
     */
    public Integer getEodQuantity() {
        return eodQuantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_order_detail.eod_quantity
     *
     * @param eodQuantity the value for eb_order_detail.eod_quantity
     *
     * @mbggenerated
     */
    public void setEodQuantity(Integer eodQuantity) {
        this.eodQuantity = eodQuantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_order_detail.eod_cost
     *
     * @return the value of eb_order_detail.eod_cost
     *
     * @mbggenerated
     */
    public BigDecimal getEodCost() {
        return eodCost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_order_detail.eod_cost
     *
     * @param eodCost the value for eb_order_detail.eod_cost
     *
     * @mbggenerated
     */
    public void setEodCost(BigDecimal eodCost) {
        this.eodCost = eodCost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eb_order_detail
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", eodId=").append(eodId);
        sb.append(", eoId=").append(eoId);
        sb.append(", epId=").append(epId);
        sb.append(", eodQuantity=").append(eodQuantity);
        sb.append(", eodCost=").append(eodCost);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eb_order_detail
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        EbOrderDetail other = (EbOrderDetail) that;
        return (this.getEodId() == null ? other.getEodId() == null : this.getEodId().equals(other.getEodId()))
            && (this.getEoId() == null ? other.getEoId() == null : this.getEoId().equals(other.getEoId()))
            && (this.getEpId() == null ? other.getEpId() == null : this.getEpId().equals(other.getEpId()))
            && (this.getEodQuantity() == null ? other.getEodQuantity() == null : this.getEodQuantity().equals(other.getEodQuantity()))
            && (this.getEodCost() == null ? other.getEodCost() == null : this.getEodCost().equals(other.getEodCost()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eb_order_detail
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getEodId() == null) ? 0 : getEodId().hashCode());
        result = prime * result + ((getEoId() == null) ? 0 : getEoId().hashCode());
        result = prime * result + ((getEpId() == null) ? 0 : getEpId().hashCode());
        result = prime * result + ((getEodQuantity() == null) ? 0 : getEodQuantity().hashCode());
        result = prime * result + ((getEodCost() == null) ? 0 : getEodCost().hashCode());
        return result;
    }
}