package io.oicp.yorick61c.domain;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class EbOrder implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_order.eo_id
     *
     * @mbggenerated
     */
    private Integer eoId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_order.eo_user_id
     *
     * @mbggenerated
     */
    private String eoUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_order.eo_user_name
     *
     * @mbggenerated
     */
    private String eoUserName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_order.eo_user_address
     *
     * @mbggenerated
     */
    private String eoUserAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_order.eo_create_time
     *
     * @mbggenerated
     */
    private Date eoCreateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_order.eo_cost
     *
     * @mbggenerated
     */
    private BigDecimal eoCost;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_order.eo_status
     *
     * @mbggenerated
     */
    private Integer eoStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_order.eo_type
     *
     * @mbggenerated
     */
    private Integer eoType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table eb_order
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_order.eo_id
     *
     * @return the value of eb_order.eo_id
     *
     * @mbggenerated
     */
    public Integer getEoId() {
        return eoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_order.eo_id
     *
     * @param eoId the value for eb_order.eo_id
     *
     * @mbggenerated
     */
    public void setEoId(Integer eoId) {
        this.eoId = eoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_order.eo_user_id
     *
     * @return the value of eb_order.eo_user_id
     *
     * @mbggenerated
     */
    public String getEoUserId() {
        return eoUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_order.eo_user_id
     *
     * @param eoUserId the value for eb_order.eo_user_id
     *
     * @mbggenerated
     */
    public void setEoUserId(String eoUserId) {
        this.eoUserId = eoUserId == null ? null : eoUserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_order.eo_user_name
     *
     * @return the value of eb_order.eo_user_name
     *
     * @mbggenerated
     */
    public String getEoUserName() {
        return eoUserName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_order.eo_user_name
     *
     * @param eoUserName the value for eb_order.eo_user_name
     *
     * @mbggenerated
     */
    public void setEoUserName(String eoUserName) {
        this.eoUserName = eoUserName == null ? null : eoUserName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_order.eo_user_address
     *
     * @return the value of eb_order.eo_user_address
     *
     * @mbggenerated
     */
    public String getEoUserAddress() {
        return eoUserAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_order.eo_user_address
     *
     * @param eoUserAddress the value for eb_order.eo_user_address
     *
     * @mbggenerated
     */
    public void setEoUserAddress(String eoUserAddress) {
        this.eoUserAddress = eoUserAddress == null ? null : eoUserAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_order.eo_create_time
     *
     * @return the value of eb_order.eo_create_time
     *
     * @mbggenerated
     */
    public Date getEoCreateTime() {
        return eoCreateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_order.eo_create_time
     *
     * @param eoCreateTime the value for eb_order.eo_create_time
     *
     * @mbggenerated
     */
    public void setEoCreateTime(Date eoCreateTime) {
        this.eoCreateTime = eoCreateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_order.eo_cost
     *
     * @return the value of eb_order.eo_cost
     *
     * @mbggenerated
     */
    public BigDecimal getEoCost() {
        return eoCost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_order.eo_cost
     *
     * @param eoCost the value for eb_order.eo_cost
     *
     * @mbggenerated
     */
    public void setEoCost(BigDecimal eoCost) {
        this.eoCost = eoCost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_order.eo_status
     *
     * @return the value of eb_order.eo_status
     *
     * @mbggenerated
     */
    public Integer getEoStatus() {
        return eoStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_order.eo_status
     *
     * @param eoStatus the value for eb_order.eo_status
     *
     * @mbggenerated
     */
    public void setEoStatus(Integer eoStatus) {
        this.eoStatus = eoStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_order.eo_type
     *
     * @return the value of eb_order.eo_type
     *
     * @mbggenerated
     */
    public Integer getEoType() {
        return eoType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_order.eo_type
     *
     * @param eoType the value for eb_order.eo_type
     *
     * @mbggenerated
     */
    public void setEoType(Integer eoType) {
        this.eoType = eoType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eb_order
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", eoId=").append(eoId);
        sb.append(", eoUserId=").append(eoUserId);
        sb.append(", eoUserName=").append(eoUserName);
        sb.append(", eoUserAddress=").append(eoUserAddress);
        sb.append(", eoCreateTime=").append(eoCreateTime);
        sb.append(", eoCost=").append(eoCost);
        sb.append(", eoStatus=").append(eoStatus);
        sb.append(", eoType=").append(eoType);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eb_order
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        EbOrder other = (EbOrder) that;
        return (this.getEoId() == null ? other.getEoId() == null : this.getEoId().equals(other.getEoId()))
            && (this.getEoUserId() == null ? other.getEoUserId() == null : this.getEoUserId().equals(other.getEoUserId()))
            && (this.getEoUserName() == null ? other.getEoUserName() == null : this.getEoUserName().equals(other.getEoUserName()))
            && (this.getEoUserAddress() == null ? other.getEoUserAddress() == null : this.getEoUserAddress().equals(other.getEoUserAddress()))
            && (this.getEoCreateTime() == null ? other.getEoCreateTime() == null : this.getEoCreateTime().equals(other.getEoCreateTime()))
            && (this.getEoCost() == null ? other.getEoCost() == null : this.getEoCost().equals(other.getEoCost()))
            && (this.getEoStatus() == null ? other.getEoStatus() == null : this.getEoStatus().equals(other.getEoStatus()))
            && (this.getEoType() == null ? other.getEoType() == null : this.getEoType().equals(other.getEoType()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eb_order
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getEoId() == null) ? 0 : getEoId().hashCode());
        result = prime * result + ((getEoUserId() == null) ? 0 : getEoUserId().hashCode());
        result = prime * result + ((getEoUserName() == null) ? 0 : getEoUserName().hashCode());
        result = prime * result + ((getEoUserAddress() == null) ? 0 : getEoUserAddress().hashCode());
        result = prime * result + ((getEoCreateTime() == null) ? 0 : getEoCreateTime().hashCode());
        result = prime * result + ((getEoCost() == null) ? 0 : getEoCost().hashCode());
        result = prime * result + ((getEoStatus() == null) ? 0 : getEoStatus().hashCode());
        result = prime * result + ((getEoType() == null) ? 0 : getEoType().hashCode());
        return result;
    }
}