package io.oicp.yorick61c.domain;

import com.fasterxml.jackson.annotation.JsonFormat;
import org.springframework.format.annotation.DateTimeFormat;

import java.io.Serializable;
import java.util.Date;

public class EbUser implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Eb_USER.EU_USER_ID
     *
     * @mbggenerated
     */
    private String euUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Eb_USER.EU_USER_NAME
     *
     * @mbggenerated
     */
    private String euUserName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Eb_USER.EU_PASSWORD
     *
     * @mbggenerated
     */
    private String euPassword;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Eb_USER.EU_SEX
     *
     * @mbggenerated
     */
    private String euSex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Eb_USER.EU_BIRTHDAY
     *
     * @mbggenerated
     */
    @DateTimeFormat(pattern="yyyy-MM-dd")
    @JsonFormat(
            pattern = "yyyy-MM-dd",
            timezone = "GMT+8"
    )
    private Date euBirthday;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Eb_USER.EU_IDENTITY_CODE
     *
     * @mbggenerated
     */
    private String euIdentityCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Eb_USER.EU_EMAIL
     *
     * @mbggenerated
     */
    private String euEmail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Eb_USER.EU_MOBILE
     *
     * @mbggenerated
     */
    private String euMobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Eb_USER.EU_ADDRESS
     *
     * @mbggenerated
     */
    private String euAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Eb_USER.EU_STATUS
     *
     * @mbggenerated
     */
    private Integer euStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table Eb_USER
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Eb_USER.EU_USER_ID
     *
     * @return the value of Eb_USER.EU_USER_ID
     *
     * @mbggenerated
     */
    public String getEuUserId() {
        return euUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Eb_USER.EU_USER_ID
     *
     * @param euUserId the value for Eb_USER.EU_USER_ID
     *
     * @mbggenerated
     */
    public void setEuUserId(String euUserId) {
        this.euUserId = euUserId == null ? null : euUserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Eb_USER.EU_USER_NAME
     *
     * @return the value of Eb_USER.EU_USER_NAME
     *
     * @mbggenerated
     */
    public String getEuUserName() {
        return euUserName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Eb_USER.EU_USER_NAME
     *
     * @param euUserName the value for Eb_USER.EU_USER_NAME
     *
     * @mbggenerated
     */
    public void setEuUserName(String euUserName) {
        this.euUserName = euUserName == null ? null : euUserName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Eb_USER.EU_PASSWORD
     *
     * @return the value of Eb_USER.EU_PASSWORD
     *
     * @mbggenerated
     */
    public String getEuPassword() {
        return euPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Eb_USER.EU_PASSWORD
     *
     * @param euPassword the value for Eb_USER.EU_PASSWORD
     *
     * @mbggenerated
     */
    public void setEuPassword(String euPassword) {
        this.euPassword = euPassword == null ? null : euPassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Eb_USER.EU_SEX
     *
     * @return the value of Eb_USER.EU_SEX
     *
     * @mbggenerated
     */
    public String getEuSex() {
        return euSex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Eb_USER.EU_SEX
     *
     * @param euSex the value for Eb_USER.EU_SEX
     *
     * @mbggenerated
     */
    public void setEuSex(String euSex) {
        this.euSex = euSex == null ? null : euSex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Eb_USER.EU_BIRTHDAY
     *
     * @return the value of Eb_USER.EU_BIRTHDAY
     *
     * @mbggenerated
     */
    public Date getEuBirthday() {
        return euBirthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Eb_USER.EU_BIRTHDAY
     *
     * @param euBirthday the value for Eb_USER.EU_BIRTHDAY
     *
     * @mbggenerated
     */
    public void setEuBirthday(Date euBirthday) {
        this.euBirthday = euBirthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Eb_USER.EU_IDENTITY_CODE
     *
     * @return the value of Eb_USER.EU_IDENTITY_CODE
     *
     * @mbggenerated
     */
    public String getEuIdentityCode() {
        return euIdentityCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Eb_USER.EU_IDENTITY_CODE
     *
     * @param euIdentityCode the value for Eb_USER.EU_IDENTITY_CODE
     *
     * @mbggenerated
     */
    public void setEuIdentityCode(String euIdentityCode) {
        this.euIdentityCode = euIdentityCode == null ? null : euIdentityCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Eb_USER.EU_EMAIL
     *
     * @return the value of Eb_USER.EU_EMAIL
     *
     * @mbggenerated
     */
    public String getEuEmail() {
        return euEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Eb_USER.EU_EMAIL
     *
     * @param euEmail the value for Eb_USER.EU_EMAIL
     *
     * @mbggenerated
     */
    public void setEuEmail(String euEmail) {
        this.euEmail = euEmail == null ? null : euEmail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Eb_USER.EU_MOBILE
     *
     * @return the value of Eb_USER.EU_MOBILE
     *
     * @mbggenerated
     */
    public String getEuMobile() {
        return euMobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Eb_USER.EU_MOBILE
     *
     * @param euMobile the value for Eb_USER.EU_MOBILE
     *
     * @mbggenerated
     */
    public void setEuMobile(String euMobile) {
        this.euMobile = euMobile == null ? null : euMobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Eb_USER.EU_ADDRESS
     *
     * @return the value of Eb_USER.EU_ADDRESS
     *
     * @mbggenerated
     */
    public String getEuAddress() {
        return euAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Eb_USER.EU_ADDRESS
     *
     * @param euAddress the value for Eb_USER.EU_ADDRESS
     *
     * @mbggenerated
     */
    public void setEuAddress(String euAddress) {
        this.euAddress = euAddress == null ? null : euAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Eb_USER.EU_STATUS
     *
     * @return the value of Eb_USER.EU_STATUS
     *
     * @mbggenerated
     */
    public Integer getEuStatus() {
        return euStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Eb_USER.EU_STATUS
     *
     * @param euStatus the value for Eb_USER.EU_STATUS
     *
     * @mbggenerated
     */
    public void setEuStatus(Integer euStatus) {
        this.euStatus = euStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Eb_USER
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", euUserId=").append(euUserId);
        sb.append(", euUserName=").append(euUserName);
        sb.append(", euPassword=").append(euPassword);
        sb.append(", euSex=").append(euSex);
        sb.append(", euBirthday=").append(euBirthday);
        sb.append(", euIdentityCode=").append(euIdentityCode);
        sb.append(", euEmail=").append(euEmail);
        sb.append(", euMobile=").append(euMobile);
        sb.append(", euAddress=").append(euAddress);
        sb.append(", euStatus=").append(euStatus);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Eb_USER
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        EbUser other = (EbUser) that;
        return (this.getEuUserId() == null ? other.getEuUserId() == null : this.getEuUserId().equals(other.getEuUserId()))
            && (this.getEuUserName() == null ? other.getEuUserName() == null : this.getEuUserName().equals(other.getEuUserName()))
            && (this.getEuPassword() == null ? other.getEuPassword() == null : this.getEuPassword().equals(other.getEuPassword()))
            && (this.getEuSex() == null ? other.getEuSex() == null : this.getEuSex().equals(other.getEuSex()))
            && (this.getEuBirthday() == null ? other.getEuBirthday() == null : this.getEuBirthday().equals(other.getEuBirthday()))
            && (this.getEuIdentityCode() == null ? other.getEuIdentityCode() == null : this.getEuIdentityCode().equals(other.getEuIdentityCode()))
            && (this.getEuEmail() == null ? other.getEuEmail() == null : this.getEuEmail().equals(other.getEuEmail()))
            && (this.getEuMobile() == null ? other.getEuMobile() == null : this.getEuMobile().equals(other.getEuMobile()))
            && (this.getEuAddress() == null ? other.getEuAddress() == null : this.getEuAddress().equals(other.getEuAddress()))
            && (this.getEuStatus() == null ? other.getEuStatus() == null : this.getEuStatus().equals(other.getEuStatus()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Eb_USER
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getEuUserId() == null) ? 0 : getEuUserId().hashCode());
        result = prime * result + ((getEuUserName() == null) ? 0 : getEuUserName().hashCode());
        result = prime * result + ((getEuPassword() == null) ? 0 : getEuPassword().hashCode());
        result = prime * result + ((getEuSex() == null) ? 0 : getEuSex().hashCode());
        result = prime * result + ((getEuBirthday() == null) ? 0 : getEuBirthday().hashCode());
        result = prime * result + ((getEuIdentityCode() == null) ? 0 : getEuIdentityCode().hashCode());
        result = prime * result + ((getEuEmail() == null) ? 0 : getEuEmail().hashCode());
        result = prime * result + ((getEuMobile() == null) ? 0 : getEuMobile().hashCode());
        result = prime * result + ((getEuAddress() == null) ? 0 : getEuAddress().hashCode());
        result = prime * result + ((getEuStatus() == null) ? 0 : getEuStatus().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Eb_USER
     *
     * @mbggenerated
     */

}